### ISSUE TITLE
Home screen two completely separate xml files 

### ISSUE THREAD

**Issue by seamus91g** [seamus91g/WordFox#7]
Home screen constraint transition uses two entirely separate xml files. 90% of the two files are the same. Instead, should use an **< include >** section to add only the unique section.

**Comment by desseepe** [comment]
I'm probably wrong on this one, but my understanding of using keyframe animations with a constraint layout is that you can use 2 layout xml files to act as your keyframes. Basically what this guy says:
https://www.youtube.com/watch?v=OHcfs6rStRo&t=15s but tbh I don't entirely understand his instructions.

And that it's seemingly not a major concern: https://robinhood.engineering/beautiful-animations-using-android-constraintlayout-eee5b72ecae3

But I see they all mention a way to animate programmatically without 2 xml files. So I'll try do that instead.

**Comment by desseepe** [comment]
This is ultimately what I ended up following (on account of not wanting to use the Kotlin code from the last 2 examples) :

https://stackoverflow.com/questions/49462293/how-to-use-constraintset-for-animation-in-android-with-java

**Comment by seamus91g** [comment]
I haven't studied your links too deeply, but first to clarify what I meant above. 

Yes you need two separate xml files, but you can presumably have a third one which contains all the stuff that is common to both. You would include that common section in both files. Then each individual xml file can also have its own unique parts. 

Pseudo example below. If I'm still missing something let me know and I'll study your links. 

**main.xml**
```
<Content main 
        < include common section >
        < include pre transition section > 
/ Content main> 

```
**main_detail.xml**
```
<Content main detail
        < include common section >
        < include post transition section > 
/ Content main detail> 

```
**common.xml**
```
<Common
        // This section is included in both pre and post
/ Common>
```

**Comment by seamus91g** [comment]
This can be closed since the home page is now restructured and no longer has the animation. For any future animations this process should be used.
